version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: whoami-satisfactory_web_1
      APP_PORT: 80

  web:
    image: wh0am1dev/umbrel-satisfactory:1.0.0@sha256:4780e3db469c64b630b15f5793472db55ecfa3d5a5b65ec10052b1d2a1699254
    restart: on-failure
    user: '1000:1000'

  server:
    image: indifferentbroccoli/satisfactory-server-docker:v1.1.0@sha256:984558aa669f69a701202f6021368bd8007ff336ad9ec277e25cd6eb2b339102
    restart: on-failure
    stop_grace_period: 30s
    ports:
      - 7777:7777/udp
      - 7777:7777/tcp
    environment:
      PUID: 1000
      PGID: 1000
    env_file:
      - ./data/.env
    volumes:
      - ${APP_DATA_DIR}/data/server-files:/satisfactory
      - ${APP_DATA_DIR}/data/server-data:/home/steam/.config/Epic/FactoryGame/Saved/SaveGames
