version: '3.7'
services:
  satisfactory:
    image: indifferentbroccoli/satisfactory-server-docker
    restart: on-failure
    stop_grace_period: 30s
    ports:
      - 7777:7777/udp
      - 7777:7777/tcp
    environment:
      PUID: 1000
      PGID: 1000
    env_file:
      - ${APP_DATA_DIR}/.env
    volumes:
      - ${APP_DATA_DIR}/data/server-files:/satisfactory
      - ${APP_DATA_DIR}/data/server-data:/home/steam/.config/Epic/FactoryGame/Saved/SaveGames
