version: '3.7'

services:
  minecraft:
    image: itzg/minecraft-server
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    environment:
      EULA: 'TRUE'
      SNOOPER_ENABLED: false
    env_file:
      - ${APP_DATA_DIR}/data/.env
    volumes:
      - ${APP_DATA_DIR}/data/server:/data
